export default [
    {
        "card_created_at": "2024-01-16 11:55:29",
        "order_id": "0040f07e8000510b",
        "file_path": null,
        "is_checked": 1,
        "status": 1,
        "remark": null,
        "category_id": 4,
        "sub_category_id": 34,
        "category_name": "Transcorp",
        "sub_category_name": "Reloadable Topup"
    },
    {
        "card_created_at": "2024-01-12 15:15:51",
        "order_id": "00d7000500005f3d",
        "file_path": null,
        "is_checked": 2,
        "status": 4,
        "remark": null,
        "category_id": 7,
        "sub_category_id": 38,
        "category_name": "Gift Vouchers",
        "sub_category_name": "Amazon"
    },
    {
        "card_created_at": "2024-01-09 15:12:34",
        "order_id": "2840254a0022d369",
        "file_path": null,
        "is_checked": 2,
        "status": 1,
        "remark": null,
        "category_id": 1,
        "sub_category_id": 6,
        "category_name": "NSDL CARD",
        "sub_category_name": "NSDL Eezib Reloadable Topup (Rupay)"
    },
    {
        "card_created_at": "2024-01-03 18:40:43",
        "order_id": "016000003a001401",
        "file_path": "uploads/cardcsv/7201734484prepaid_transcorp_virtual (1).csv",
        "is_checked": 3,
        "status": 1,
        "remark": null,
        "category_id": 4,
        "sub_category_id": 22,
        "category_name": "Transcorp",
        "sub_category_name": "Eezib Transcorp Virtual Prepaid Card"
    },
    {
        "card_created_at": "2024-01-02 19:23:22",
        "order_id": "b60ca000000d02bd",
        "file_path": null,
        "is_checked": 3,
        "status": 1,
        "remark": null,
        "category_id": 5,
        "sub_category_id": 30,
        "category_name": "NSDL",
        "sub_category_name": "NSDL Eezib Prepaid Physical Card (Visa)"
    },
    {
        "card_created_at": "2024-01-02 19:14:37",
        "order_id": "0d00800706471f00",
        "file_path": null,
        "is_checked": 3,
        "status": 1,
        "remark": null,
        "category_id": 4,
        "sub_category_id": 34,
        "category_name": "Transcorp",
        "sub_category_name": "Reloadable Topup"
    },
    {
        "card_created_at": "2024-01-02 17:12:31",
        "order_id": "0007500000bf87f3",
        "file_path": null,
        "is_checked": 3,
        "status": 1,
        "remark": null,
        "category_id": 5,
        "sub_category_id": 25,
        "category_name": "NSDL",
        "sub_category_name": "NSDL Eezib Prepaid Virtual Card (Rupay)"
    },
    {
        "card_created_at": "2024-01-02 17:07:22",
        "order_id": "0050016c0c180900",
        "file_path": null,
        "is_checked": 3,
        "status": 1,
        "remark": null,
        "category_id": 4,
        "sub_category_id": 34,
        "category_name": "Transcorp",
        "sub_category_name": "Reloadable Topup"
    },
    {
        "card_created_at": "2024-01-02 17:07:10",
        "order_id": "0f007a007f0bc009",
        "file_path": null,
        "is_checked": 3,
        "status": 1,
        "remark": null,
        "category_id": 4,
        "sub_category_id": 34,
        "category_name": "Transcorp",
        "sub_category_name": "Reloadable Topup"
    },
    {
        "card_created_at": "2024-01-02 17:05:59",
        "order_id": "006b000b10702b03",
        "file_path": null,
        "is_checked": 3,
        "status": 1,
        "remark": null,
        "category_id": 4,
        "sub_category_id": 34,
        "category_name": "Transcorp",
        "sub_category_name": "Reloadable Topup"
    },
    {
        "card_created_at": "2024-01-02 16:47:13",
        "order_id": "0004090104e00000",
        "file_path": null,
        "is_checked": 3,
        "status": 1,
        "remark": null,
        "category_id": 5,
        "sub_category_id": 30,
        "category_name": "NSDL",
        "sub_category_name": "NSDL Eezib Prepaid Physical Card (Visa)"
    },
    {
        "card_created_at": "2024-01-02 12:12:55",
        "order_id": "30010007000d07ca",
        "file_path": null,
        "is_checked": 3,
        "status": 1,
        "remark": null,
        "category_id": 7,
        "sub_category_id": 38,
        "category_name": "Gift Vouchers",
        "sub_category_name": "Amazon"
    },
    {
        "card_created_at": "2023-12-29 17:19:29",
        "order_id": "5c0080ef00200034",
        "file_path": null,
        "is_checked": 2,
        "status": 1,
        "remark": null,
        "category_id": 5,
        "sub_category_id": 25,
        "category_name": "NSDL",
        "sub_category_name": "NSDL Eezib Prepaid Virtual Card (Rupay)"
    },
    {
        "card_created_at": "2023-12-29 17:18:51",
        "order_id": "0c007000002c19a7",
        "file_path": null,
        "is_checked": 3,
        "status": 1,
        "remark": null,
        "category_id": 5,
        "sub_category_id": 25,
        "category_name": "NSDL",
        "sub_category_name": "NSDL Eezib Prepaid Virtual Card (Rupay)"
    },
    {
        "card_created_at": "2023-12-29 17:08:10",
        "order_id": "05b09f001700bd00",
        "file_path": null,
        "is_checked": 3,
        "status": 1,
        "remark": null,
        "category_id": 5,
        "sub_category_id": 25,
        "category_name": "NSDL",
        "sub_category_name": "NSDL Eezib Prepaid Virtual Card (Rupay)"
    },
    {
        "card_created_at": "2023-12-29 14:32:28",
        "order_id": "ff000093000b0062",
        "file_path": null,
        "is_checked": 2,
        "status": 3,
        "remark": "testing",
        "category_id": 5,
        "sub_category_id": 30,
        "category_name": "NSDL",
        "sub_category_name": "NSDL Eezib Prepaid Physical Card (Visa)"
    },
    {
        "card_created_at": "2023-12-29 14:31:36",
        "order_id": "000c5800f590070f",
        "file_path": null,
        "is_checked": 2,
        "status": 1,
        "remark": null,
        "category_id": 5,
        "sub_category_id": 29,
        "category_name": "NSDL",
        "sub_category_name": "NSDL Eezib Prepaid Physical Card (Rupay)"
    },
    {
        "card_created_at": "2023-12-29 14:26:55",
        "order_id": "20003062e0024400",
        "file_path": null,
        "is_checked": 2,
        "status": 1,
        "remark": null,
        "category_id": 5,
        "sub_category_id": 32,
        "category_name": "NSDL",
        "sub_category_name": "NSDL Eezib KYC Physical Card (Visa)"
    },
    {
        "card_created_at": "2023-12-29 14:24:19",
        "order_id": "70800d008a003220",
        "file_path": null,
        "is_checked": 2,
        "status": 1,
        "remark": null,
        "category_id": 5,
        "sub_category_id": 31,
        "category_name": "NSDL",
        "sub_category_name": "NSDL Eezib KYC Physical Card (Rupay)"
    },
    {
        "card_created_at": "2023-12-29 12:32:40",
        "order_id": "0b03800e086a0900",
        "file_path": null,
        "is_checked": 2,
        "status": 1,
        "remark": null,
        "category_id": 5,
        "sub_category_id": 26,
        "category_name": "NSDL",
        "sub_category_name": "NSDL Eezib Prepaid Virtual Card (Visa)"
    },
    {
        "card_created_at": "2023-12-29 12:27:56",
        "order_id": "00010d09be000099",
        "file_path": null,
        "is_checked": 3,
        "status": 1,
        "remark": null,
        "category_id": 5,
        "sub_category_id": 26,
        "category_name": "NSDL",
        "sub_category_name": "NSDL Eezib Prepaid Virtual Card (Visa)"
    },
    {
        "card_created_at": "2023-12-29 12:05:24",
        "order_id": "03000200304290fa",
        "file_path": null,
        "is_checked": 2,
        "status": 1,
        "remark": null,
        "category_id": 5,
        "sub_category_id": 25,
        "category_name": "NSDL",
        "sub_category_name": "NSDL Eezib Prepaid Virtual Card (Rupay)"
    },
    {
        "card_created_at": "2023-12-29 11:57:31",
        "order_id": "00000906400013f0",
        "file_path": null,
        "is_checked": 2,
        "status": 1,
        "remark": null,
        "category_id": 5,
        "sub_category_id": 25,
        "category_name": "NSDL",
        "sub_category_name": "NSDL Eezib Prepaid Virtual Card (Rupay)"
    },
    {
        "card_created_at": "2023-12-29 11:45:51",
        "order_id": "8e0090703000c0d3",
        "file_path": "uploads/cardcsv/0530815137format.csv",
        "is_checked": 1,
        "status": 1,
        "remark": null,
        "category_id": 5,
        "sub_category_id": 25,
        "category_name": "NSDL",
        "sub_category_name": "NSDL Eezib Prepaid Virtual Card (Rupay)"
    },
    {
        "card_created_at": "2023-12-28 15:10:23",
        "order_id": "4400800460010103",
        "file_path": null,
        "is_checked": 3,
        "status": 1,
        "remark": null,
        "category_id": 4,
        "sub_category_id": 34,
        "category_name": "Transcorp",
        "sub_category_name": "Reloadable Topup"
    },
    {
        "card_created_at": "2023-12-28 15:09:53",
        "order_id": "224020000c06020b",
        "file_path": null,
        "is_checked": 3,
        "status": 1,
        "remark": null,
        "category_id": 4,
        "sub_category_id": 34,
        "category_name": "Transcorp",
        "sub_category_name": "Reloadable Topup"
    },
    {
        "card_created_at": "2023-12-28 15:06:23",
        "order_id": "3be0000008009983",
        "file_path": null,
        "is_checked": 3,
        "status": 1,
        "remark": null,
        "category_id": 3,
        "sub_category_id": 40,
        "category_name": "Fino",
        "sub_category_name": "Reloadable Topup"
    },
    {
        "card_created_at": "2023-12-28 14:54:02",
        "order_id": "0213000450b3d000",
        "file_path": null,
        "is_checked": 3,
        "status": 1,
        "remark": null,
        "category_id": 3,
        "sub_category_id": 40,
        "category_name": "Fino",
        "sub_category_name": "Reloadable Topup"
    },
    {
        "card_created_at": "2023-12-27 12:52:46",
        "order_id": "0b3000e702800302",
        "file_path": null,
        "is_checked": 2,
        "status": 1,
        "remark": null,
        "category_id": 6,
        "sub_category_id": 35,
        "category_name": "Euronet",
        "sub_category_name": "Euronet Eezib Prepaid Virtual Card (Rupay)"
    },
    {
        "card_created_at": "2023-12-27 12:51:45",
        "order_id": "054ab000c800a000",
        "file_path": null,
        "is_checked": 1,
        "status": 1,
        "remark": null,
        "category_id": 6,
        "sub_category_id": 35,
        "category_name": "Euronet",
        "sub_category_name": "Euronet Eezib Prepaid Virtual Card (Rupay)"
    },
    {
        "card_created_at": "2023-12-26 15:39:14",
        "order_id": "0e0e070c008c0010",
        "file_path": "uploads/cardcsv/PAWAN-Voucher-2023-12-26-15-39-13.csv",
        "is_checked": 2,
        "status": 4,
        "remark": null,
        "category_id": 4,
        "sub_category_id": 33,
        "category_name": "Transcorp",
        "sub_category_name": "Eezib Transcorp Virtual Reloadable card"
    },
    {
        "card_created_at": "2023-12-26 15:37:40",
        "order_id": "000010fa07e87300",
        "file_path": "uploads/cardcsv/PAWAN-Voucher-2023-12-26-15-37-39.csv",
        "is_checked": 1,
        "status": 0,
        "remark": null,
        "category_id": 4,
        "sub_category_id": 33,
        "category_name": "Transcorp",
        "sub_category_name": "Eezib Transcorp Virtual Reloadable card"
    },
    {
        "card_created_at": "2023-12-26 15:37:16",
        "order_id": "0107008f50cc0400",
        "file_path": "uploads/cardcsv/PAWAN-Voucher-2023-12-26-15-37-16.csv",
        "is_checked": 1,
        "status": 0,
        "remark": null,
        "category_id": 4,
        "sub_category_id": 33,
        "category_name": "Transcorp",
        "sub_category_name": "Eezib Transcorp Virtual Reloadable card"
    },
    {
        "card_created_at": "2023-12-26 15:30:27",
        "order_id": "0040f9f000800b0a",
        "file_path": null,
        "is_checked": 1,
        "status": 0,
        "remark": null,
        "category_id": 4,
        "sub_category_id": 33,
        "category_name": "Transcorp",
        "sub_category_name": "Eezib Transcorp Virtual Reloadable card"
    },
    {
        "card_created_at": "2023-12-26 15:08:44",
        "order_id": "0a00001007a017e0",
        "file_path": "uploads/cardcsv/PAWAN-Voucher-2023-12-26-15-08-43.csv",
        "is_checked": 2,
        "status": 4,
        "remark": null,
        "category_id": 4,
        "sub_category_id": 22,
        "category_name": "Transcorp",
        "sub_category_name": "Eezib Transcorp Virtual Prepaid Card"
    },
    {
        "card_created_at": "2023-12-26 14:44:40",
        "order_id": "00bf8400b6802000",
        "file_path": "uploads/cardcsv/PAWAN-Voucher-2023-12-26-14-44-40.csv",
        "is_checked": 2,
        "status": 4,
        "remark": null,
        "category_id": 4,
        "sub_category_id": 22,
        "category_name": "Transcorp",
        "sub_category_name": "Eezib Transcorp Virtual Prepaid Card"
    },
    {
        "card_created_at": "2023-12-26 14:42:03",
        "order_id": "0005200000506f75",
        "file_path": "uploads/cardcsv/PAWAN-Voucher-2023-12-26-14-42-03.csv",
        "is_checked": -1,
        "status": -1,
        "remark": null,
        "category_id": 4,
        "sub_category_id": 22,
        "category_name": "Transcorp",
        "sub_category_name": "Eezib Transcorp Virtual Prepaid Card"
    },
    {
        "card_created_at": "2023-12-26 14:41:52",
        "order_id": "0f705028000300d8",
        "file_path": "uploads/cardcsv/PAWAN-Voucher-2023-12-26-14-41-52.csv",
        "is_checked": -1,
        "status": -1,
        "remark": null,
        "category_id": 4,
        "sub_category_id": 22,
        "category_name": "Transcorp",
        "sub_category_name": "Eezib Transcorp Virtual Prepaid Card"
    },
    {
        "card_created_at": "2023-12-26 14:39:33",
        "order_id": "04700fb0b000039c",
        "file_path": "uploads/cardcsv/PAWAN-Voucher-2023-12-26-14-39-33.csv",
        "is_checked": -1,
        "status": -1,
        "remark": null,
        "category_id": 4,
        "sub_category_id": 22,
        "category_name": "Transcorp",
        "sub_category_name": "Eezib Transcorp Virtual Prepaid Card"
    },
    {
        "card_created_at": "2023-12-26 14:37:51",
        "order_id": "570000d601080330",
        "file_path": "uploads/cardcsv/PAWAN-Voucher-2023-12-26-14-37-50.csv",
        "is_checked": 3,
        "status": 3,
        "remark": "DOB Is not proper Rejected by system",
        "category_id": 4,
        "sub_category_id": 22,
        "category_name": "Transcorp",
        "sub_category_name": "Eezib Transcorp Virtual Prepaid Card"
    },
    {
        "card_created_at": "2023-12-26 14:36:56",
        "order_id": "a0008e0bf005b070",
        "file_path": "uploads/cardcsv/PAWAN-Voucher-2023-12-26-14-36-56.csv",
        "is_checked": 3,
        "status": 3,
        "remark": "DOB Is not proper Rejected by system",
        "category_id": 4,
        "sub_category_id": 22,
        "category_name": "Transcorp",
        "sub_category_name": "Eezib Transcorp Virtual Prepaid Card"
    },
    {
        "card_created_at": "2023-12-26 14:36:24",
        "order_id": "80003905002cbf00",
        "file_path": "uploads/cardcsv/PAWAN-Voucher-2023-12-26-14-36-24.csv",
        "is_checked": 3,
        "status": 3,
        "remark": "DOB Is not proper Rejected by system",
        "category_id": 4,
        "sub_category_id": 22,
        "category_name": "Transcorp",
        "sub_category_name": "Eezib Transcorp Virtual Prepaid Card"
    },
    {
        "card_created_at": "2023-12-26 14:21:57",
        "order_id": "050012400f086003",
        "file_path": "uploads/cardcsv/PAWAN-Voucher-2023-12-26-14-21-57.csv",
        "is_checked": 3,
        "status": 3,
        "remark": "DOB Is not proper Rejected by system",
        "category_id": 4,
        "sub_category_id": 22,
        "category_name": "Transcorp",
        "sub_category_name": "Eezib Transcorp Virtual Prepaid Card"
    },
    {
        "card_created_at": "2023-12-26 14:21:44",
        "order_id": "005d0c0108d00eb0",
        "file_path": "uploads/cardcsv/PAWAN-Voucher-2023-12-26-14-21-44.csv",
        "is_checked": 3,
        "status": 3,
        "remark": "DOB Is not proper Rejected by system",
        "category_id": 4,
        "sub_category_id": 22,
        "category_name": "Transcorp",
        "sub_category_name": "Eezib Transcorp Virtual Prepaid Card"
    },
    {
        "card_created_at": "2023-12-26 14:21:02",
        "order_id": "010300f040e00294",
        "file_path": "uploads/cardcsv/PAWAN-Voucher-2023-12-26-14-21-02.csv",
        "is_checked": 3,
        "status": 3,
        "remark": "DOB Is not proper Rejected by system",
        "category_id": 4,
        "sub_category_id": 22,
        "category_name": "Transcorp",
        "sub_category_name": "Eezib Transcorp Virtual Prepaid Card"
    },
    {
        "card_created_at": "2023-12-26 13:08:36",
        "order_id": "d0060000fd0564c0",
        "file_path": "uploads/cardcsv/PAWAN-Voucher-2023-12-26-13-08-36.csv",
        "is_checked": 3,
        "status": 3,
        "remark": "DOB Is not proper Rejected by system",
        "category_id": 4,
        "sub_category_id": 22,
        "category_name": "Transcorp",
        "sub_category_name": "Eezib Transcorp Virtual Prepaid Card"
    },
    {
        "card_created_at": "2023-12-26 13:08:27",
        "order_id": "2890206490d00000",
        "file_path": "uploads/cardcsv/PAWAN-Voucher-2023-12-26-13-08-27.csv",
        "is_checked": -1,
        "status": -1,
        "remark": null,
        "category_id": 4,
        "sub_category_id": 22,
        "category_name": "Transcorp",
        "sub_category_name": "Eezib Transcorp Virtual Prepaid Card"
    },
    {
        "card_created_at": "2023-12-21 22:04:43",
        "order_id": "8ddd000700302200",
        "file_path": null,
        "is_checked": 3,
        "status": 1,
        "remark": null,
        "category_id": 7,
        "sub_category_id": 38,
        "category_name": "Gift Vouchers",
        "sub_category_name": "Amazon"
    },
    {
        "card_created_at": "2023-12-21 17:35:20",
        "order_id": "0708c00080025508",
        "file_path": null,
        "is_checked": 3,
        "status": 1,
        "remark": null,
        "category_id": 7,
        "sub_category_id": 38,
        "category_name": "Gift Vouchers",
        "sub_category_name": "Amazon"
    },
    {
        "card_created_at": "2023-12-21 16:48:30",
        "order_id": "0a001b000000ca52",
        "file_path": null,
        "is_checked": 3,
        "status": 1,
        "remark": null,
        "category_id": 7,
        "sub_category_id": 38,
        "category_name": "Gift Vouchers",
        "sub_category_name": "Amazon"
    },
    {
        "card_created_at": "2023-12-21 15:57:11",
        "order_id": "0000fcf0f0001b60",
        "file_path": "uploads/cardcsv/1354713014prepaid_transcorp_virtual.csv",
        "is_checked": 3,
        "status": 1,
        "remark": null,
        "category_id": 4,
        "sub_category_id": 22,
        "category_name": "Transcorp",
        "sub_category_name": "Eezib Transcorp Virtual Prepaid Card"
    },
    {
        "card_created_at": "2023-12-21 15:24:14",
        "order_id": "400000e000d10182",
        "file_path": "uploads/cardcsv/5451013274prepaid_transcorp_virtual.csv",
        "is_checked": 3,
        "status": 1,
        "remark": null,
        "category_id": 4,
        "sub_category_id": 22,
        "category_name": "Transcorp",
        "sub_category_name": "Eezib Transcorp Virtual Prepaid Card"
    },
    {
        "card_created_at": "2023-12-21 15:21:27",
        "order_id": "901050e002f008b0",
        "file_path": "uploads/cardcsv/7312082175prepaid_transcorp_virtual.csv",
        "is_checked": 3,
        "status": 1,
        "remark": null,
        "category_id": 4,
        "sub_category_id": 22,
        "category_name": "Transcorp",
        "sub_category_name": "Eezib Transcorp Virtual Prepaid Card"
    },
    {
        "card_created_at": "2023-12-21 14:33:16",
        "order_id": "15b20c1c10984e0e",
        "file_path": "uploads/cardcsv/1971430396format (14).csv",
        "is_checked": 3,
        "status": 1,
        "remark": null,
        "category_id": 1,
        "sub_category_id": 21,
        "category_name": "NSDL CARD",
        "sub_category_name": "NSDL Eezib Prepaid Virtual Card (Rupay)(817359)"
    },
    {
        "card_created_at": "2023-12-21 13:14:38",
        "order_id": "76080700ba00f0e0",
        "file_path": "voucher_data/PAWAN-Voucher-2023-12-21-13-14-38.xlsx",
        "is_checked": 2,
        "status": 4,
        "remark": null,
        "category_id": 7,
        "sub_category_id": 38,
        "category_name": "Gift Vouchers",
        "sub_category_name": "Amazon"
    },
    {
        "card_created_at": "2023-12-20 15:21:12",
        "order_id": "000080f05010a023",
        "file_path": "voucher_data/PAWAN-Voucher-2023-12-20-15-21-12.xlsx",
        "is_checked": 1,
        "status": 1,
        "remark": null,
        "category_id": 7,
        "sub_category_id": 38,
        "category_name": "Gift Vouchers",
        "sub_category_name": "Amazon"
    },
    {
        "card_created_at": "2023-12-16 11:12:46",
        "order_id": "9e000800060040fa",
        "file_path": "voucher_data/PAWAN-Voucher-2023-12-16-11-12-46.xlsx",
        "is_checked": 1,
        "status": 1,
        "remark": null,
        "category_id": 7,
        "sub_category_id": 38,
        "category_name": "Gift Vouchers",
        "sub_category_name": "Amazon"
    },
    {
        "card_created_at": "2023-12-13 10:59:02",
        "order_id": "9daac040e000000d",
        "file_path": null,
        "is_checked": 2,
        "status": 4,
        "remark": null,
        "category_id": 3,
        "sub_category_id": 40,
        "category_name": "Fino",
        "sub_category_name": "Reloadable Topup"
    },
    {
        "card_created_at": "2023-12-11 18:21:12",
        "order_id": "06e00000040450b2",
        "file_path": null,
        "is_checked": 2,
        "status": 4,
        "remark": null,
        "category_id": 3,
        "sub_category_id": 40,
        "category_name": "Fino",
        "sub_category_name": "Reloadable Topup"
    }
]
